<?php

namespace Modules\Reservation\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReservationDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $qcMain = DB::table('branches')->where('code', 'QC_MAIN')->value('id');

        // Only one RESA officer login exists in the seeded user set — she encodes
        // for every individual/group agent code. Accounting picks records up
        // once they are forwarded.
        $jhona      = DB::table('users')->where('email', 'jhona@amkor.ph')->value('id');
        $accounting = DB::table('users')->where('email', 'accounting@amkor.ph')->value('id');

        // ── Reservation Bookings ────────────────────────────────────────────────
        DB::table('reservation_bookings')->delete();

        $bookings = [
            [
                'booking_no'        => 'RES-2026-001',
                'date'               => '2026-01-08',
                'agent_code'         => 'RT',
                'client_name'        => 'Manila Solutions Corp.',
                'date_of_birth'      => null,
                'contact_number'     => '09175551001',
                'email'              => 'travel@manilasolutions.com',
                'corporate_account'  => 'Manila Solutions Corp.',
                'destination'        => 'Bangkok, Thailand',
                'airline'            => 'Philippine Airlines',
                'travel_date'        => '2026-02-15',
                'return_date'        => '2026-02-22',
                'pax_count'          => 6,
                'service_type'       => 'package',
                'transaction_type'   => 'corporate',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'Corporate team-building trip — 5 nights Bangkok incl. hotel, tours, and roundtrip airfare via PAL',
                'inclusions'         => 'Roundtrip airfare (PAL), 5N Centara Grand at CentralWorld (Deluxe), airport transfers, city tour, half-day Ayutthaya tour, travel insurance',
                'exclusions'         => 'Personal expenses, optional tours, tips',
                'selling_price'      => 156000.00,
                'net_payable'        => 124800.00,
                'income'             => 31200.00,
                'excess'             => 0.00,
                'insurance_nett'     => 3600.00,
                'acr'                => 'ACR-2026-001',
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-02-01',
                'soa_number'         => 'SOA-2026-001',
                'po_number'          => 'PO-MS-2026-001',
                'si_number'          => 'SI-2026-001',
                'ar_number'          => 'AR-2026-001',
                'or_number'          => 'OR-2026-001',
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-01-15 14:30:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-01-10 10:00:00',
                'confirmed_by'       => $jhona,
                'remarks'            => '50% deposit of PHP 78,000 received Jan 10; balance settled Feb 1.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-002',
                'date'               => '2026-01-20',
                'agent_code'         => 'RP',
                'client_name'        => 'Juan Dela Cruz',
                'date_of_birth'      => '1985-04-12',
                'contact_number'     => '09185552002',
                'email'              => null,
                'corporate_account'  => null,
                'destination'        => 'Cebu',
                'airline'            => 'Cebu Pacific',
                'travel_date'        => '2026-02-10',
                'return_date'        => '2026-02-12',
                'pax_count'          => 2,
                'service_type'       => 'package',
                'transaction_type'   => 'fit',
                'source'             => 'Walk-in',
                'particulars'        => 'Weekend getaway — Cebu 2D1N package with hotel and airfare',
                'inclusions'         => 'Roundtrip airfare (5J), 1N Radisson Blu Cebu (Standard), airport transfer',
                'exclusions'         => 'Meals, personal expenses',
                'selling_price'      => 28000.00,
                'net_payable'        => 22400.00,
                'income'             => 5600.00,
                'excess'             => 0.00,
                'insurance_nett'     => null,
                'acr'                => null,
                'mode_of_payment'    => 'cash',
                'payment_due_date'   => '2026-02-05',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => 'SI-2026-002',
                'ar_number'          => 'AR-2026-002',
                'or_number'          => 'OR-2026-002',
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-01-25 11:00:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-01-22 09:30:00',
                'confirmed_by'       => $jhona,
                'remarks'            => 'Full payment received in cash.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-003',
                'date'               => '2026-02-03',
                'agent_code'         => 'MMT',
                'client_name'        => 'Philippine Tech Inc.',
                'date_of_birth'      => null,
                'contact_number'     => '09175553003',
                'email'              => 'travel@phtech.com',
                'corporate_account'  => 'Philippine Tech Inc.',
                'destination'        => 'Singapore',
                'airline'            => 'Singapore Airlines',
                'travel_date'        => '2026-03-10',
                'return_date'        => '2026-03-15',
                'pax_count'          => 9,
                'service_type'       => 'package',
                'transaction_type'   => 'group',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'Annual company retreat — 5 nights Singapore with business hotel, city tour, and team dinner',
                'inclusions'         => 'Roundtrip airfare (SQ), 5N Orchard Hotel (Superior), airport transfers, half-day city tour, group dinner at Newton Food Centre',
                'exclusions'         => 'Personal expenses, optional attractions, visa fees (PH passport holders visa-free)',
                'selling_price'      => 198000.00,
                'net_payable'        => 158400.00,
                'income'             => 39600.00,
                'excess'             => 0.00,
                'insurance_nett'     => 5400.00,
                'acr'                => 'ACR-2026-003',
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-03-01',
                'soa_number'         => 'SOA-2026-003',
                'po_number'          => 'PO-PT-2026-003',
                'si_number'          => 'SI-2026-003',
                'ar_number'          => 'AR-2026-003',
                'or_number'          => null,
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-02-10 09:00:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-02-05 14:00:00',
                'confirmed_by'       => $jhona,
                'remarks'            => '50% deposit paid; balance due March 1.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-004',
                'date'               => '2026-02-14',
                'agent_code'         => 'EJ',
                'client_name'        => 'Maria Garcia',
                'date_of_birth'      => '1990-07-22',
                'contact_number'     => '09285554004',
                'email'              => 'maria.garcia@email.com',
                'corporate_account'  => null,
                'destination'        => 'Boracay',
                'airline'            => 'Philippine Airlines',
                'travel_date'        => '2026-03-20',
                'return_date'        => '2026-03-23',
                'pax_count'          => 4,
                'service_type'       => 'package',
                'transaction_type'   => 'fit',
                'source'             => 'Referral',
                'particulars'        => 'Family vacation — Boracay 3D2N package',
                'inclusions'         => 'Roundtrip airfare (PAL MNL–KLO), 2N Crimson Resort (Deluxe Garden), airport transfers, island hopping tour',
                'exclusions'         => 'Meals, water sports, personal expenses',
                'selling_price'      => 52000.00,
                'net_payable'        => 41600.00,
                'income'             => 10400.00,
                'excess'             => 0.00,
                'insurance_nett'     => 2400.00,
                'acr'                => null,
                'mode_of_payment'    => 'credit_card',
                'payment_due_date'   => '2026-03-10',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => null,
                'ar_number'          => null,
                'or_number'          => null,
                'status'             => 'inquiry',
                'forwarded_to_accounting'    => false,
                'forwarded_to_accounting_at' => null,
                'forwarded_to_accounting_by' => null,
                'confirmed_at'       => null,
                'confirmed_by'       => null,
                'remarks'            => 'Awaiting deposit to confirm booking.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $jhona,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-005',
                'date'               => '2026-03-01',
                'agent_code'         => 'JMMT',
                'client_name'        => 'BDO Unibank Inc.',
                'date_of_birth'      => null,
                'contact_number'     => '09175555005',
                'email'              => 'corptravel@bdo.com.ph',
                'corporate_account'  => 'BDO Unibank Inc.',
                'destination'        => 'Tokyo, Japan',
                'airline'            => 'Japan Airlines',
                'travel_date'        => '2026-04-05',
                'return_date'        => '2026-04-12',
                'pax_count'          => 4,
                'service_type'       => 'package',
                'transaction_type'   => 'corporate',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'Executive study trip — Tokyo 7 nights, business hotel, Shinkansen day trip',
                'inclusions'         => 'Roundtrip airfare (JL), 7N Shinjuku Prince Hotel (Standard), Suica cards, Hakone day tour, Narita Express passes',
                'exclusions'         => 'Meals, personal expenses, Japan visa fees',
                'selling_price'      => 280000.00,
                'net_payable'        => 224000.00,
                'income'             => 56000.00,
                'excess'             => 0.00,
                'insurance_nett'     => 6800.00,
                'acr'                => 'ACR-2026-005',
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-03-25',
                'soa_number'         => 'SOA-2026-005',
                'po_number'          => 'PO-BDO-2026-005',
                'si_number'          => 'SI-2026-005',
                'ar_number'          => 'AR-2026-005',
                'or_number'          => 'OR-2026-005',
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-03-08 15:00:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-03-04 11:00:00',
                'confirmed_by'       => $jhona,
                'remarks'            => 'Visas being processed separately through the Visa & Documentation department.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-006',
                'date'               => '2026-03-15',
                'agent_code'         => 'KG',
                'client_name'        => 'Roberto Santos',
                'date_of_birth'      => '1978-11-03',
                'contact_number'     => '09995556006',
                'email'              => 'rsantos@gmail.com',
                'corporate_account'  => null,
                'destination'        => 'Palawan',
                'airline'            => 'Air Juan',
                'travel_date'        => '2026-04-18',
                'return_date'        => '2026-04-22',
                'pax_count'          => 3,
                'service_type'       => 'other',
                'transaction_type'   => 'fit',
                'source'             => 'Social media (Facebook page)',
                'particulars'        => 'El Nido 4D3N land + sea package — no airfare',
                'inclusions'         => 'Shared boat transfers from Puerto Princesa to El Nido, 3N Villa Libertad (Garden), island hopping Tours A & C, full board meals',
                'exclusions'         => 'Airfare, personal expenses, entrance fees',
                'selling_price'      => 36000.00,
                'net_payable'        => 28800.00,
                'income'             => 7200.00,
                'excess'             => 0.00,
                'insurance_nett'     => null,
                'acr'                => null,
                'mode_of_payment'    => 'cash',
                'payment_due_date'   => '2026-04-10',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => 'SI-2026-006',
                'ar_number'          => 'AR-2026-006',
                'or_number'          => 'OR-2026-006',
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-03-22 10:30:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-03-18 13:00:00',
                'confirmed_by'       => $jhona,
                'remarks'            => 'Full payment settled in cash.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-007',
                'date'               => '2026-04-05',
                'agent_code'         => 'AL',
                'client_name'        => 'Jollibee Foods Corporation',
                'date_of_birth'      => null,
                'contact_number'     => '09175557007',
                'email'              => 'travel@jollibee.com.ph',
                'corporate_account'  => 'Jollibee Foods Corporation',
                'destination'        => 'Kuala Lumpur, Malaysia',
                'airline'            => 'AirAsia',
                'travel_date'        => '2026-05-08',
                'return_date'        => '2026-05-11',
                'pax_count'          => 12,
                'service_type'       => 'package',
                'transaction_type'   => 'group',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'JFC leadership summit — KL 3D2N with venue, hotel, and airport transfers',
                'inclusions'         => 'Roundtrip airfare (AK), 2N Hilton Kuala Lumpur (King), airport transfers, city tour, conference room (Day 2)',
                'exclusions'         => 'Meals outside itinerary, personal expenses',
                'selling_price'      => 312000.00,
                'net_payable'        => 249600.00,
                'income'             => 62400.00,
                'excess'             => 0.00,
                'insurance_nett'     => 7200.00,
                'acr'                => 'ACR-2026-007',
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-04-28',
                'soa_number'         => 'SOA-2026-007',
                'po_number'          => 'PO-JFC-2026-007',
                'si_number'          => 'SI-2026-007',
                'ar_number'          => 'AR-2026-007',
                'or_number'          => null,
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-04-12 16:00:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-04-08 10:30:00',
                'confirmed_by'       => $jhona,
                'remarks'            => 'SOA issued; 60% downpayment received via BDO wire transfer.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-008',
                'date'               => '2026-04-20',
                'agent_code'         => 'CM',
                'client_name'        => 'Elena Reyes',
                'date_of_birth'      => '1995-08-30',
                'contact_number'     => '09285558008',
                'email'              => 'elena.reyes@outlook.com',
                'corporate_account'  => null,
                'destination'        => 'Seoul, South Korea',
                'airline'            => 'Korean Air',
                'travel_date'        => '2026-05-20',
                'return_date'        => '2026-05-27',
                'pax_count'          => 2,
                'service_type'       => 'package',
                'transaction_type'   => 'fit',
                'source'             => 'Referral',
                'particulars'        => 'Seoul honeymoon package — 7 nights with Nanta show, Jeju ferry, and K-culture tour',
                'inclusions'         => 'Roundtrip airfare (KE), 7N Hotel Myeongdong (Deluxe), Nanta show tickets, Jeju day ferry package, T-money cards, travel insurance',
                'exclusions'         => 'Korean visa (applied separately), meals, personal expenses',
                'selling_price'      => 95000.00,
                'net_payable'        => 76000.00,
                'income'             => 19000.00,
                'excess'             => 0.00,
                'insurance_nett'     => 2800.00,
                'acr'                => null,
                'mode_of_payment'    => 'credit_card',
                'payment_due_date'   => '2026-05-10',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => 'SI-2026-008',
                'ar_number'          => 'AR-2026-008',
                'or_number'          => null,
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => false,
                'forwarded_to_accounting_at' => null,
                'forwarded_to_accounting_by' => null,
                'confirmed_at'       => '2026-04-23 14:30:00',
                'confirmed_by'       => $jhona,
                'remarks'            => 'Credit card payment pending bank clearance.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $jhona,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-009',
                'date'               => '2026-05-10',
                'agent_code'         => 'KL',
                'client_name'        => 'Ayala Land Inc.',
                'date_of_birth'      => null,
                'contact_number'     => '09175559009',
                'email'              => 'group.travel@ayalaland.com',
                'corporate_account'  => 'Ayala Land Inc.',
                'destination'        => 'Bali, Indonesia',
                'airline'            => 'Garuda Indonesia',
                'travel_date'        => '2026-06-12',
                'return_date'        => '2026-06-17',
                'pax_count'          => 15,
                'service_type'       => 'package',
                'transaction_type'   => 'blocking',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'Ayala Annual Incentive Trip — Bali 5D4N group package, seats blocked ahead of confirmation',
                'inclusions'         => 'Roundtrip airfare (GA), 4N Alaya Resort Ubud (Pool Villa, group bloc), private airport transfers, Kecak dance, Tegallalang rice terrace tour, group farewell dinner, travel insurance',
                'exclusions'         => 'Personal expenses, optional ATV tours, laundry',
                'selling_price'      => 525000.00,
                'net_payable'        => 420000.00,
                'income'             => 105000.00,
                'excess'             => 0.00,
                'insurance_nett'     => 13500.00,
                'acr'                => 'ACR-2026-009',
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-06-01',
                'soa_number'         => 'SOA-2026-009',
                'po_number'          => 'PO-ALI-2026-009',
                'si_number'          => 'SI-2026-009',
                'ar_number'          => 'AR-2026-009',
                'or_number'          => null,
                'status'             => 'confirmed',
                'forwarded_to_accounting'    => true,
                'forwarded_to_accounting_at' => '2026-05-18 10:00:00',
                'forwarded_to_accounting_by' => $jhona,
                'confirmed_at'       => '2026-05-14 09:00:00',
                'confirmed_by'       => $jhona,
                'remarks'            => '40% deposit received; balance due June 1.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-010',
                'date'               => '2026-05-28',
                'agent_code'         => 'JR',
                'client_name'        => 'Carlos Mendoza',
                'date_of_birth'      => '1982-02-14',
                'contact_number'     => '09185550010',
                'email'              => 'carlos.mendoza@yahoo.com',
                'corporate_account'  => null,
                'destination'        => 'Osaka, Japan',
                'airline'            => 'AirAsia',
                'travel_date'        => '2026-07-04',
                'return_date'        => '2026-07-10',
                'pax_count'          => 3,
                'service_type'       => 'package',
                'transaction_type'   => 'fit',
                'source'             => 'Online inquiry',
                'particulars'        => 'Family Japan summer trip — Osaka/Kyoto/Nara 6 nights',
                'inclusions'         => 'Roundtrip airfare (AK MNL–KIX), 3N Cross Hotel Osaka (Twin), 3N Kyoto Tower Hotel (Twin), Nara day tour, Osaka Amazing Pass (3-day), travel insurance',
                'exclusions'         => 'Japan visa, meals, personal expenses',
                'selling_price'      => 145000.00,
                'net_payable'        => 116000.00,
                'income'             => 29000.00,
                'excess'             => 0.00,
                'insurance_nett'     => 4500.00,
                'acr'                => null,
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-06-20',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => null,
                'ar_number'          => null,
                'or_number'          => null,
                'status'             => 'quoted',
                'forwarded_to_accounting'    => false,
                'forwarded_to_accounting_at' => null,
                'forwarded_to_accounting_by' => null,
                'confirmed_at'       => null,
                'confirmed_by'       => null,
                'remarks'            => 'Japan visa appointment scheduled June 10 via Visa & Documentation dept.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $jhona,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-011',
                'date'               => '2026-04-10',
                'agent_code'         => 'EB',
                'client_name'        => 'Metro Bank Employees Association',
                'date_of_birth'      => null,
                'contact_number'     => '09175551011',
                'email'              => 'mbea@metrobank.com.ph',
                'corporate_account'  => 'Metro Bank Employees Association',
                'destination'        => 'Hong Kong',
                'airline'            => 'Cathay Pacific',
                'travel_date'        => '2026-05-15',
                'return_date'        => '2026-05-19',
                'pax_count'          => 10,
                'service_type'       => 'ticketing',
                'transaction_type'   => 'group',
                'source'             => 'Corporate account — existing client',
                'particulars'        => 'Flight-only bookings for HK shopping trip',
                'inclusions'         => 'Roundtrip airfare (CX), 23 kg baggage allowance per pax',
                'exclusions'         => 'Hotel, transfers, meals',
                'selling_price'      => 150000.00,
                'net_payable'        => 135000.00,
                'income'             => 15000.00,
                'excess'             => 0.00,
                'insurance_nett'     => null,
                'acr'                => null,
                'mode_of_payment'    => 'bank_transfer',
                'payment_due_date'   => '2026-05-01',
                'soa_number'         => 'SOA-2026-011',
                'po_number'          => 'PO-MBEA-2026-011',
                'si_number'          => null,
                'ar_number'          => null,
                'or_number'          => null,
                'status'             => 'cancelled',
                'forwarded_to_accounting'    => false,
                'forwarded_to_accounting_at' => null,
                'forwarded_to_accounting_by' => null,
                'confirmed_at'       => null,
                'confirmed_by'       => null,
                'remarks'            => 'Client cancelled due to scheduling conflict before deposit was paid. No refund liability — booking was never ticketed.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $jhona,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'booking_no'        => 'RES-2026-012',
                'date'               => '2026-06-05',
                'agent_code'         => 'JF',
                'client_name'        => 'Sarah Lopez',
                'date_of_birth'      => '1992-09-18',
                'contact_number'     => '09175551012',
                'email'              => null,
                'corporate_account'  => null,
                'destination'        => 'Baguio',
                'airline'            => null,
                'travel_date'        => '2026-06-20',
                'return_date'        => '2026-06-22',
                'pax_count'          => 2,
                'service_type'       => 'hotel',
                'transaction_type'   => 'fit',
                'source'             => 'Walk-in',
                'particulars'        => 'Hotel-only booking for a weekend trip, client driving up themselves',
                'inclusions'         => '2N The Manor at Camp John Hay (Deluxe)',
                'exclusions'         => 'Transportation, meals',
                'selling_price'      => 14000.00,
                'net_payable'        => 11200.00,
                'income'             => 2800.00,
                'excess'             => 0.00,
                'insurance_nett'     => null,
                'acr'                => null,
                'mode_of_payment'    => 'credit_card',
                'payment_due_date'   => '2026-06-15',
                'soa_number'         => null,
                'po_number'          => null,
                'si_number'          => null,
                'ar_number'          => null,
                'or_number'          => null,
                'status'             => 'quoted',
                'forwarded_to_accounting'    => false,
                'forwarded_to_accounting_at' => null,
                'forwarded_to_accounting_by' => null,
                'confirmed_at'       => null,
                'confirmed_by'       => null,
                'remarks'            => 'Quotation sent; awaiting client confirmation.',
                'audit_remarks'      => null,
                'branch_id'          => $qcMain,
                'created_by'         => $jhona,
                'updated_by'         => $jhona,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        DB::table('reservation_bookings')->insert($bookings);

        // ── Airline Rates ────────────────────────────────────────────────────────
        DB::table('airline_rates')->delete();

        $rates = [
            ['airline' => 'Philippine Airlines', 'origin' => 'MNL', 'destination' => 'CEB', 'fare_class' => 'Economy',  'rate' => 3200.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Base economy, no checked baggage'],
            ['airline' => 'Philippine Airlines', 'origin' => 'MNL', 'destination' => 'CEB', 'fare_class' => 'Economy',  'rate' => 3600.00,  'currency' => 'PHP', 'effective_date' => '2026-05-01', 'remarks' => 'Rate increase effective May — fuel surcharge adjustment'],
            ['airline' => 'Philippine Airlines', 'origin' => 'MNL', 'destination' => 'CEB', 'fare_class' => 'Business', 'rate' => 9800.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Business class with lounge access'],
            ['airline' => 'Cebu Pacific',         'origin' => 'MNL', 'destination' => 'CEB', 'fare_class' => 'Go Lite',  'rate' => 1850.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => '7 kg carry-on only, no checked baggage'],
            ['airline' => 'AirAsia',              'origin' => 'MNL', 'destination' => 'CEB', 'fare_class' => 'Economy',  'rate' => 1650.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Promo fare, non-refundable'],
            ['airline' => 'Philippine Airlines', 'origin' => 'MNL', 'destination' => 'NRT', 'fare_class' => 'Economy',  'rate' => 28500.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip economy incl. taxes'],
            ['airline' => 'Japan Airlines',       'origin' => 'MNL', 'destination' => 'NRT', 'fare_class' => 'Economy',  'rate' => 30000.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip economy incl. taxes'],
            ['airline' => 'AirAsia',              'origin' => 'MNL', 'destination' => 'KUL', 'fare_class' => 'Economy',  'rate' => 8500.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip incl. airport tax'],
            ['airline' => 'Singapore Airlines',   'origin' => 'MNL', 'destination' => 'SIN', 'fare_class' => 'Economy',  'rate' => 18500.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip, 23 kg baggage included'],
            ['airline' => 'Korean Air',           'origin' => 'MNL', 'destination' => 'ICN', 'fare_class' => 'Economy',  'rate' => 22000.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip, 23 kg baggage included'],
            ['airline' => 'Korean Air',           'origin' => 'MNL', 'destination' => 'ICN', 'fare_class' => 'Economy',  'rate' => 24500.00, 'currency' => 'PHP', 'effective_date' => '2026-06-01', 'remarks' => 'Peak summer season rate'],
            ['airline' => 'Garuda Indonesia',     'origin' => 'MNL', 'destination' => 'DPS', 'fare_class' => 'Economy',  'rate' => 16500.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip Bali, 20 kg baggage'],
            ['airline' => 'Philippine Airlines', 'origin' => 'MNL', 'destination' => 'BKK', 'fare_class' => 'Economy',  'rate' => 14000.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip Bangkok, 23 kg baggage'],
            ['airline' => 'Cebu Pacific',         'origin' => 'MNL', 'destination' => 'KLO', 'fare_class' => 'Economy',  'rate' => 2800.00,  'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'MNL–Kalibo for Boracay, 20 kg baggage'],
            ['airline' => 'Cathay Pacific',       'origin' => 'MNL', 'destination' => 'HKG', 'fare_class' => 'Economy',  'rate' => 13500.00, 'currency' => 'PHP', 'effective_date' => '2026-01-01', 'remarks' => 'Roundtrip Hong Kong, 23 kg baggage'],
        ];

        foreach ($rates as $rate) {
            DB::table('airline_rates')->insert(array_merge($rate, [
                'created_by' => $accounting,
                'updated_by' => $accounting,
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
