<?php

namespace Modules\Disbursement\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DisbursementDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now    = now();
        $qcMain = DB::table('branches')->where('code', 'QC_MAIN')->value('id');

        $accounting = DB::table('users')->where('email', 'accounting@amkor.ph')->value('id');
        $coo        = DB::table('users')->where('email', 'coo@amkor.ph')->value('id');

        DB::table('disbursement_entries')->delete();
        DB::table('vouchers')->delete();

        // ── Vouchers ──────────────────────────────────────────────────────────
        $vouchers = [
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00001',
                'date'                => '2026-01-25',
                'payee'               => 'Philippine Airlines',
                'payee_address'       => 'PNB Financial Center, Pres. Diosdado Macapagal Blvd., Pasay City',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'Full payment — 6 pax Bangkok roundtrip airfare (RES-2026-001)',
                'account_code'        => '5010-001',
                'account_description' => 'Airfare Payable — Domestic/International',
                'currency'            => 'PHP',
                'amount'              => 112800.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-01-14 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-01-15 14:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-01-25 11:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-01-14 10:30:00',
                'remarks'             => 'BDO bank deposit; deposit slip on file.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00002',
                'date'                => '2026-01-10',
                'payee'               => 'Japan Embassy Manila',
                'payee_address'       => '2627 Roxas Blvd., Pasay City, Metro Manila',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'Visa filing fees — 3 applicants (Mendoza, Fernandez, batch) @ PHP 3,200 each',
                'account_code'        => '5020-001',
                'account_description' => 'Visa Fees Payable',
                'currency'            => 'PHP',
                'amount'              => 9600.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-01-09 09:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-01-09 14:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-01-10 09:30:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-01-09 09:30:00',
                'remarks'             => 'Cash payment at embassy window.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00003',
                'date'                => '2026-01-16',
                'payee'               => 'VFS Global Philippines',
                'payee_address'       => '6/F Zuellig Bldg., Makati Ave. cor. Paseo de Roxas, Makati City',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'VFS Global service fee — UK Standard Visitor Visa, Santos',
                'account_code'        => '5020-001',
                'account_description' => 'Visa Fees Payable',
                'currency'            => 'PHP',
                'amount'              => 8500.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-01-15 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-01-15 15:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-01-16 09:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-01-15 10:30:00',
                'remarks'             => 'BDO bank deposit; deposit slip on file.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00004',
                'date'                => '2026-03-20',
                'payee'               => 'Japan Airlines',
                'payee_address'       => '4/F Pacific Star Bldg., Makati Ave., Makati City',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'Full settlement — 4 pax NRT roundtrip airfare (RES-2026-005)',
                'account_code'        => '5010-001',
                'account_description' => 'Airfare Payable — Domestic/International',
                'currency'            => 'PHP',
                'amount'              => 196000.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-03-07 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-03-08 09:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-03-20 11:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-03-07 10:30:00',
                'remarks'             => 'BDO bank deposit; deposit slip on file.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00005',
                'date'                => '2026-04-07',
                'payee'               => 'US Embassy Manila (MRV Fee)',
                'payee_address'       => '1201 Roxas Blvd., Ermita, Manila',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'MRV application fee — US B1/B2 visa, Aquino (SI-V-2026-008); USD cash',
                'account_code'        => '5020-001',
                'account_description' => 'Visa Fees Payable',
                'currency'            => 'USD',
                'amount'              => 0.00,
                'amount_usd'          => 245.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-04-04 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-04-05 09:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-04-07 09:30:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-04-04 10:30:00',
                'remarks'             => 'USD 245 disbursed from USD petty cash fund.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'check',
                'voucher_no'          => 'CHV-2026-00001',
                'date'                => '2026-02-05',
                'payee'               => 'MERALCO',
                'payee_address'       => 'Lopez Building, Meralco Ave., Ortigas Center, Pasig City',
                'check_no'            => 'BDO-CK-112233',
                'bank_name'           => 'BDO Unibank',
                'check_date'          => '2026-02-05',
                'details'             => 'Electric bill — January 2026, main office (Acct 1234-5678-9)',
                'account_code'        => '5030-002',
                'account_description' => 'Utilities Expense — Electricity',
                'currency'            => 'PHP',
                'amount'              => 28450.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-02-03 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-02-04 09:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-02-05 10:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-02-03 10:30:00',
                'remarks'             => 'Check issued and delivered to MERALCO payment center.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'check',
                'voucher_no'          => 'CHV-2026-00002',
                'date'                => '2026-03-05',
                'payee'               => 'Globe Telecom',
                'payee_address'       => 'The Globe Tower, 32nd Street corner 7th Avenue, BGC, Taguig City',
                'check_no'            => 'BDO-CK-112244',
                'bank_name'           => 'BDO Unibank',
                'check_date'          => '2026-03-05',
                'details'             => 'Globe Postpaid — Feb 2026, main office landline + broadband (Acct 09XX-XXXXXXX)',
                'account_code'        => '5030-003',
                'account_description' => 'Utilities Expense — Telecom',
                'currency'            => 'PHP',
                'amount'              => 8900.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-03-03 10:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-03-04 09:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-03-05 10:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-03-03 10:30:00',
                'remarks'             => 'Check delivered to Globe business payment desk.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'type'                => 'cash',
                'voucher_no'          => 'CV-2026-00006',
                'date'                => '2026-02-20',
                'payee'               => 'KVAC (Korea Visa Application Center)',
                'payee_address'       => 'G/F Ecoplaza Bldg., 2305 Don Chino Roces Ave., Makati City',
                'check_no'            => null,
                'bank_name'           => null,
                'check_date'          => null,
                'details'             => 'Korea Tourist Visa filing fee — Lim (SI-V-2026-005)',
                'account_code'        => '5020-001',
                'account_description' => 'Visa Fees Payable',
                'currency'            => 'PHP',
                'amount'              => 3800.00,
                'amount_usd'          => 0.00,
                'amount_jpy'          => 0.00,
                'approval_status'     => 'released',
                'checked_by'          => $accounting,
                'checked_at'          => '2026-02-19 14:00:00',
                'approved_by'         => $coo,
                'approved_at'         => '2026-02-19 16:00:00',
                'released_by'         => $accounting,
                'released_at'         => '2026-02-20 09:00:00',
                'pdf_generated'       => true,
                'pdf_generated_at'    => '2026-02-19 14:30:00',
                'remarks'             => 'Cash payment at KVAC counter.',
                'branch_id'           => $qcMain,
                'created_by'          => $accounting,
                'updated_by'          => $accounting,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
        ];

        DB::table('vouchers')->insert($vouchers);

        // Reload voucher IDs
        $cv1  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00001')->value('id');
        $cv2  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00002')->value('id');
        $cv3  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00003')->value('id');
        $cv4  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00004')->value('id');
        $cv5  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00005')->value('id');
        $chv1 = DB::table('vouchers')->where('voucher_no', 'CHV-2026-00001')->value('id');
        $chv2 = DB::table('vouchers')->where('voucher_no', 'CHV-2026-00002')->value('id');
        $cv6  = DB::table('vouchers')->where('voucher_no', 'CV-2026-00006')->value('id');

        // Link voucher_id back to payables
        DB::table('payables')->where('requisition_no', 'REQ-2026-001')->update(['voucher_id' => $cv1]);
        DB::table('payables')->where('requisition_no', 'REQ-2026-002')->update(['voucher_id' => $cv2]);
        DB::table('payables')->where('requisition_no', 'REQ-2026-004')->update(['voucher_id' => $cv4]);
        DB::table('payables')->where('requisition_no', 'REQ-2026-005')->update(['voucher_id' => $cv5]);
        DB::table('payables')->where('requisition_no', 'REQ-2026-008')->update(['voucher_id' => $cv3]);
        DB::table('payables')->where('requisition_no', 'REQ-2026-010')->update(['voucher_id' => $cv6]);

        // ── Disbursement Entries ───────────────────────────────────────────────
        $entries = [
            // Cash disbursements
            [
                'date'               => '2026-01-25',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00001',
                'voucher_id'         => $cv1,
                'payee'              => 'Philippine Airlines',
                'description'        => '6 pax BKK roundtrip airfare — RES-2026-001',
                'account_code'       => '5010-001',
                'currency'           => 'PHP',
                'amount'             => 112800.00,
                'fund_type'          => 'cash_on_bank',
                'remarks'            => 'BDO bank deposit',
                'access_file_period' => '2026-01-31',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-01-10',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00002',
                'voucher_id'         => $cv2,
                'payee'              => 'Japan Embassy Manila',
                'description'        => 'Japan Tourist Visa filing fees × 3 applicants',
                'account_code'       => '5020-001',
                'currency'           => 'PHP',
                'amount'             => 9600.00,
                'fund_type'          => 'cash_on_hand',
                'remarks'            => 'Cash at embassy window',
                'access_file_period' => '2026-01-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-01-16',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00003',
                'voucher_id'         => $cv3,
                'payee'              => 'VFS Global Philippines',
                'description'        => 'VFS service fee — UK visa, Santos',
                'account_code'       => '5020-001',
                'currency'           => 'PHP',
                'amount'             => 8500.00,
                'fund_type'          => 'cash_on_bank',
                'remarks'            => 'BDO bank deposit',
                'access_file_period' => '2026-01-31',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            // Check disbursements
            [
                'date'               => '2026-02-05',
                'category'           => 'check',
                'reference_no'       => 'CHV-2026-00001',
                'voucher_id'         => $chv1,
                'payee'              => 'MERALCO',
                'description'        => 'Electric bill — January 2026, main office',
                'account_code'       => '5030-002',
                'currency'           => 'PHP',
                'amount'             => 28450.00,
                'fund_type'          => 'cash_on_bank',
                'remarks'            => 'BDO Check BDO-CK-112233',
                'access_file_period' => '2026-02-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-02-20',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00006',
                'voucher_id'         => $cv6,
                'payee'              => 'KVAC Philippines',
                'description'        => 'Korea Tourist Visa filing fee — Lim',
                'account_code'       => '5020-001',
                'currency'           => 'PHP',
                'amount'             => 3800.00,
                'fund_type'          => 'cash_on_hand',
                'remarks'            => 'Cash at KVAC counter',
                'access_file_period' => '2026-02-28',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-03-05',
                'category'           => 'check',
                'reference_no'       => 'CHV-2026-00002',
                'voucher_id'         => $chv2,
                'payee'              => 'Globe Telecom',
                'description'        => 'Globe Postpaid — February 2026 bill',
                'account_code'       => '5030-003',
                'currency'           => 'PHP',
                'amount'             => 8900.00,
                'fund_type'          => 'cash_on_bank',
                'remarks'            => 'BDO Check BDO-CK-112244',
                'access_file_period' => '2026-03-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-03-20',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00004',
                'voucher_id'         => $cv4,
                'payee'              => 'Japan Airlines',
                'description'        => '4 pax NRT roundtrip — RES-2026-005',
                'account_code'       => '5010-001',
                'currency'           => 'PHP',
                'amount'             => 196000.00,
                'fund_type'          => 'cash_on_bank',
                'remarks'            => 'BDO bank deposit',
                'access_file_period' => '2026-03-31',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-04-07',
                'category'           => 'cash',
                'reference_no'       => 'CV-2026-00005',
                'voucher_id'         => $cv5,
                'payee'              => 'US Embassy Manila',
                'description'        => 'MRV fee USD 245 — Aquino B1/B2 visa',
                'account_code'       => '5020-001',
                'currency'           => 'USD',
                'amount'             => 245.00,
                'fund_type'          => 'petty_cash',
                'remarks'            => 'USD cash from petty cash fund',
                'access_file_period' => '2026-04-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            // Liaison / admin entries
            [
                'date'               => '2026-01-20',
                'category'           => 'liaison_admin',
                'reference_no'       => 'LA-2026-001',
                'voucher_id'         => null,
                'payee'              => 'Petty Cash — Liaison',
                'description'        => 'Parking & toll fees — document delivery BIR QC Jan 15–20',
                'account_code'       => '5040-001',
                'currency'           => 'PHP',
                'amount'             => 1250.00,
                'fund_type'          => 'petty_cash',
                'remarks'            => 'Receipts attached to petty cash voucher.',
                'access_file_period' => '2026-01-31',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-02-10',
                'category'           => 'liaison_banks',
                'reference_no'       => 'LB-2026-001',
                'voucher_id'         => null,
                'payee'              => 'Petty Cash — Banks Liaison',
                'description'        => 'Bank errands: BDO Cubao, BPI Eastwood — Feb 10 deposits & withdrawals',
                'account_code'       => '5040-002',
                'currency'           => 'PHP',
                'amount'             => 850.00,
                'fund_type'          => 'petty_cash',
                'remarks'            => 'Transpo receipts on file.',
                'access_file_period' => '2026-02-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-03-12',
                'category'           => 'liaison_admin',
                'reference_no'       => 'LA-2026-002',
                'voucher_id'         => null,
                'payee'              => 'Petty Cash — Liaison',
                'description'        => 'Office supplies replenishment — printer ink, folders, stamps (Mar 12)',
                'account_code'       => '5050-001',
                'currency'           => 'PHP',
                'amount'             => 3200.00,
                'fund_type'          => 'petty_cash',
                'remarks'            => 'Official receipts attached.',
                'access_file_period' => '2026-03-15',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'date'               => '2026-04-15',
                'category'           => 'liaison_banks',
                'reference_no'       => 'LB-2026-002',
                'voucher_id'         => null,
                'payee'              => 'Petty Cash — Banks Liaison',
                'description'        => 'Bank errands: BDO Cubao, Metrobank QC — Apr 15 IATA deposit run',
                'account_code'       => '5040-002',
                'currency'           => 'PHP',
                'amount'             => 650.00,
                'fund_type'          => 'petty_cash',
                'remarks'            => 'Transpo receipts on file.',
                'access_file_period' => '2026-04-30',
                'branch_id'          => $qcMain,
                'created_by'         => $accounting,
                'updated_by'         => $accounting,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        DB::table('disbursement_entries')->insert($entries);
    }
}
