<?php

namespace Modules\BillsMonitoring\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BillsMonitoringDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now    = now();
        $qcMain = DB::table('branches')->where('code', 'QC_MAIN')->value('id');

        $accounting = DB::table('users')->where('email', 'accounting@amkor.ph')->value('id');
        $coo        = DB::table('users')->where('email', 'coo@amkor.ph')->value('id');
        $gsm        = DB::table('users')->where('email', 'gsm@amkor.ph')->value('id');

        DB::table('bills')->delete();

        $base = [
            'voucher_id'      => null,
            'payment_date'    => null,
            'mode_of_payment' => 'bank_deposit',
            'remarks'         => null,
            'audit_remarks'   => null,
            'checked_by'      => null,
            'checked_at'      => null,
            'approved_by'     => null,
            'approved_at'     => null,
            'released_by'     => null,
            'released_at'     => null,
            'branch_id'       => $qcMain,
            'created_by'      => $accounting,
            'updated_by'      => $accounting,
            'created_at'      => $now,
            'updated_at'      => $now,
        ];

        $bills = [

            // ══════════════════════════════════════════════════════════════════
            // UTILITIES — PAID / RELEASED
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — January 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 18450.75,
                'due_date'        => '2026-01-25',
                'payment_date'    => '2026-01-22',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-15 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-16 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-22 11:00:00',
                'remarks'         => 'Main office electricity — Jan 2026 billing period.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — January 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4200.00,
                'due_date'        => '2026-01-28',
                'payment_date'    => '2026-01-24',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-19 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-24 09:30:00',
                'remarks'         => '5 postpaid lines (main office); auto-charged to BDO Corporate Visa.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — January 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-01-30',
                'payment_date'    => '2026-01-27',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-20 10:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-21 09:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-27 10:00:00',
                'remarks'         => 'Main office fiber broadband — 300 Mbps plan.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — February 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 19820.50,
                'due_date'        => '2026-02-25',
                'payment_date'    => '2026-02-20',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-15 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-16 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-20 11:00:00',
                'remarks'         => 'Slightly higher than Jan due to additional AC usage.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — February 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4200.00,
                'due_date'        => '2026-02-28',
                'payment_date'    => '2026-02-24',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-19 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-24 09:30:00',
                'remarks'         => 'Auto-charged; no changes to plan.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — February 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-02-28',
                'payment_date'    => '2026-02-25',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-20 10:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-21 09:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-25 10:00:00',
                'remarks'         => 'No interruptions this month.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — March 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 21340.00,
                'due_date'        => '2026-03-25',
                'payment_date'    => '2026-03-20',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-15 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-16 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-20 11:00:00',
                'remarks'         => 'Summer month — higher AC load.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — April 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 24185.25,
                'due_date'        => '2026-04-25',
                'payment_date'    => '2026-04-22',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-04-15 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-04-16 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-04-22 11:00:00',
                'remarks'         => 'Peak summer bill — highest this year.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — March 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4200.00,
                'due_date'        => '2026-03-28',
                'payment_date'    => '2026-03-24',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-19 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-24 09:30:00',
                'remarks'         => 'No changes to plan.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — April 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4850.00,
                'due_date'        => '2026-04-28',
                'payment_date'    => '2026-04-23',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-04-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-04-19 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-04-23 09:30:00',
                'remarks'         => 'Slight increase — excess data charges for one line.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — March 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-03-30',
                'payment_date'    => '2026-03-27',
                'mode_of_payment' => 'credit_card',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-22 10:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-23 09:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-27 10:00:00',
                'remarks'         => 'No issues; auto-settled via credit card.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // MEMBERSHIP / PERMITS — PAID
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'membership',
                'name'            => 'IATA Annual Membership — 2026',
                'provider'        => 'IATA (International Air Transport Association)',
                'account_no'      => 'IATA-MBR-AMKOR-2026',
                'amount'          => 285000.00,
                'due_date'        => '2026-01-31',
                'payment_date'    => '2026-01-28',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-10 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-12 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-28 11:00:00',
                'remarks'         => 'Annual IATA membership renewal — CY2026. Critical for BSP accreditation.',
            ]),

            array_merge($base, [
                'bill_type'       => 'membership',
                'name'            => 'PhilSTA Annual Dues — 2026',
                'provider'        => 'Philippine Travel Agencies Association (PhilSTA)',
                'account_no'      => 'PHILSTA-2026-AMKOR',
                'amount'          => 12000.00,
                'due_date'        => '2026-02-28',
                'payment_date'    => '2026-02-22',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-10 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-12 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-22 11:00:00',
                'remarks'         => 'Annual PhilSTA membership dues for 2026.',
            ]),

            array_merge($base, [
                'bill_type'       => 'membership',
                'name'            => 'TMAP Annual Dues — 2026',
                'provider'        => 'Travel Management Association of the Philippines (TMAP)',
                'account_no'      => 'TMAP-AMKOR-2026',
                'amount'          => 8500.00,
                'due_date'        => '2026-03-31',
                'payment_date'    => '2026-03-25',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-15 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-16 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-25 11:00:00',
                'remarks'         => 'TMAP annual dues 2026.',
            ]),

            array_merge($base, [
                'bill_type'       => 'permit',
                'name'            => 'Business Permit Renewal — QC 2026',
                'provider'        => 'Quezon City Local Government',
                'account_no'      => 'BPLO-QC-2026-AMKOR',
                'amount'          => 42600.00,
                'due_date'        => '2026-01-20',
                'payment_date'    => '2026-01-18',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-08 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-09 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-18 11:00:00',
                'remarks'         => 'Annual business permit renewal — paid at BPLO Quezon City.',
            ]),

            array_merge($base, [
                'bill_type'       => 'permit',
                'name'            => 'DOT Tourism Accreditation — 2026',
                'provider'        => 'Department of Tourism (DOT)',
                'account_no'      => 'DOT-ACCRED-2026-AMKOR',
                'amount'          => 15000.00,
                'due_date'        => '2026-02-15',
                'payment_date'    => '2026-02-12',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-05 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-06 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-12 11:00:00',
                'remarks'         => 'DOT tourism enterprise accreditation renewal — CY2026.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // INSURANCE PREMIUMS — PAID
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Fire & General Insurance — Q1 2026',
                'provider'        => 'Malayan Insurance Co., Inc.',
                'account_no'      => 'MAL-POL-2026-QC-001',
                'amount'          => 18500.00,
                'due_date'        => '2026-01-31',
                'payment_date'    => '2026-01-28',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-20 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-28 11:00:00',
                'remarks'         => 'Q1 premium — fire, theft, and general liability policy for QC office.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Fire & General Insurance — Q2 2026',
                'provider'        => 'Malayan Insurance Co., Inc.',
                'account_no'      => 'MAL-POL-2026-QC-001',
                'amount'          => 18500.00,
                'due_date'        => '2026-04-30',
                'payment_date'    => '2026-04-25',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-04-18 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-04-20 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-04-25 11:00:00',
                'remarks'         => 'Q2 premium — same policy; no changes.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Group HMO — March 2026',
                'provider'        => 'Maxicare Healthcare Corporation',
                'account_no'      => 'MAXI-GRP-AMKOR-2026',
                'amount'          => 32400.00,
                'due_date'        => '2026-03-15',
                'payment_date'    => '2026-03-12',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-05 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-06 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-12 11:00:00',
                'remarks'         => 'Monthly group HMO premium — 12 enrolled employees.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Group HMO — April 2026',
                'provider'        => 'Maxicare Healthcare Corporation',
                'account_no'      => 'MAXI-GRP-AMKOR-2026',
                'amount'          => 32400.00,
                'due_date'        => '2026-04-15',
                'payment_date'    => '2026-04-11',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-04-05 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-04-06 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-04-11 11:00:00',
                'remarks'         => 'No additions or removals this month.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // SUPPLIES — PAID
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'supplies',
                'name'            => 'Office Supplies — January 2026',
                'provider'        => 'National Bookstore Corporate',
                'account_no'      => null,
                'amount'          => 6850.00,
                'due_date'        => '2026-01-31',
                'payment_date'    => '2026-01-28',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-01-25 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-01-26 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-01-28 11:00:00',
                'remarks'         => 'Bond paper, pens, folders, and printer ink.',
            ]),

            array_merge($base, [
                'bill_type'       => 'supplies',
                'name'            => 'Office Supplies — February 2026',
                'provider'        => 'National Bookstore Corporate',
                'account_no'      => null,
                'amount'          => 5200.00,
                'due_date'        => '2026-02-28',
                'payment_date'    => '2026-02-25',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-02-22 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-02-23 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-02-25 11:00:00',
                'remarks'         => 'Reduced from Jan — no major replenishment needed.',
            ]),

            array_merge($base, [
                'bill_type'       => 'supplies',
                'name'            => 'Toner Cartridges — Q1 2026',
                'provider'        => 'Epson Philippines',
                'account_no'      => 'EPSON-AMKOR-QC-2026',
                'amount'          => 11200.00,
                'due_date'        => '2026-03-31',
                'payment_date'    => '2026-03-28',
                'mode_of_payment' => 'cash',
                'status'          => 'paid',
                'approval_status' => 'released',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-03-20 09:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-03-21 10:00:00',
                'released_by'     => $accounting,
                'released_at'     => '2026-03-28 11:00:00',
                'remarks'         => '4 units ink tank cartridges (L6490). High usage due to visa docs.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // MAY 2026 — CHECKED (AWAITING APPROVAL)
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — May 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 22560.00,
                'due_date'        => '2026-05-25',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'pending',
                'approval_status' => 'checked',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-05-15 09:00:00',
                'remarks'         => 'May billing — awaiting COO approval for release.',
                'audit_remarks'   => 'Verified against MERALCO billing statement; amount matches.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — May 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4200.00,
                'due_date'        => '2026-05-28',
                'mode_of_payment' => 'credit_card',
                'status'          => 'pending',
                'approval_status' => 'checked',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-05-18 09:00:00',
                'remarks'         => 'No plan changes this month.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Group HMO — May 2026',
                'provider'        => 'Maxicare Healthcare Corporation',
                'account_no'      => 'MAXI-GRP-AMKOR-2026',
                'amount'          => 35640.00,
                'due_date'        => '2026-05-15',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'pending',
                'approval_status' => 'checked',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-05-05 09:00:00',
                'remarks'         => 'Increased — 1 new employee enrolled effective May 1.',
                'audit_remarks'   => 'Premium increase from 32,400 to 35,640 — 1 new enrollee confirmed with HR.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // JUNE 2026 — PENDING (CURRENT / UPCOMING)
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'MERALCO — June 2026',
                'provider'        => 'Manila Electric Company (MERALCO)',
                'account_no'      => 'MERALCO-1234567890',
                'amount'          => 21800.00,
                'due_date'        => '2026-06-25',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'pending',
                'approval_status' => 'pending',
                'remarks'         => 'June billing received — for processing.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'Globe Postpaid — June 2026',
                'provider'        => 'Globe Telecom',
                'account_no'      => 'GLOB-0917-AMKOR-01',
                'amount'          => 4200.00,
                'due_date'        => '2026-06-28',
                'mode_of_payment' => 'credit_card',
                'status'          => 'pending',
                'approval_status' => 'pending',
                'remarks'         => 'Received; for approval.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — June 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-06-30',
                'mode_of_payment' => 'credit_card',
                'status'          => 'pending',
                'approval_status' => 'pending',
                'remarks'         => 'Auto-billed; for processing.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Group HMO — June 2026',
                'provider'        => 'Maxicare Healthcare Corporation',
                'account_no'      => 'MAXI-GRP-AMKOR-2026',
                'amount'          => 35640.00,
                'due_date'        => '2026-06-15',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'pending',
                'approval_status' => 'pending',
                'remarks'         => 'Monthly premium — same enrollment as May.',
            ]),

            array_merge($base, [
                'bill_type'       => 'premium',
                'name'            => 'Fire & General Insurance — Q3 2026',
                'provider'        => 'Malayan Insurance Co., Inc.',
                'account_no'      => 'MAL-POL-2026-QC-001',
                'amount'          => 18500.00,
                'due_date'        => '2026-07-31',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'pending',
                'approval_status' => 'pending',
                'remarks'         => 'Q3 premium due July 31 — for early preparation.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // OVERDUE
            // ══════════════════════════════════════════════════════════════════

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — April 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-04-30',
                'mode_of_payment' => 'credit_card',
                'status'          => 'overdue',
                'approval_status' => 'approved',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-04-22 10:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-04-23 09:00:00',
                'remarks'         => 'Auto-charge failed — credit card expired. Manual payment needed.',
                'audit_remarks'   => 'Card expired; coordinating with PLDT for manual payment. May reconnect fees apply.',
            ]),

            array_merge($base, [
                'bill_type'       => 'utility',
                'name'            => 'PLDT Fiber — May 2026',
                'provider'        => 'PLDT Inc.',
                'account_no'      => 'PLDT-FIBER-0028374651',
                'amount'          => 3299.00,
                'due_date'        => '2026-05-30',
                'mode_of_payment' => 'bank_deposit',
                'status'          => 'overdue',
                'approval_status' => 'approved',
                'checked_by'      => $accounting,
                'checked_at'      => '2026-05-22 10:00:00',
                'approved_by'     => $coo,
                'approved_at'     => '2026-05-23 09:00:00',
                'remarks'         => 'Carried over from April issue; pending manual settlement.',
                'audit_remarks'   => 'PLDT sent disconnection notice May 28. Need to settle both April + May together.',
            ]),

            array_merge($base, [
                'bill_type'       => 'supplies',
                'name'            => 'Office Supplies — May 2026',
                'provider'        => 'National Bookstore Corporate',
                'account_no'      => null,
                'amount'          => 7480.00,
                'due_date'        => '2026-05-31',
                'mode_of_payment' => 'cash',
                'status'          => 'overdue',
                'approval_status' => 'pending',
                'remarks'         => 'Received goods; invoice unpaid. Vendor following up.',
            ]),
        ];

        DB::table('bills')->insert($bills);
    }
}
