<?php

namespace Modules\AccountsReceivable\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountsReceivableDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now        = now();
        $qcMain     = DB::table('branches')->where('code', 'QC_MAIN')->value('id');
        $visaCentre = DB::table('branches')->where('code', 'VISA_CENTRE')->value('id');
        $ormoc      = DB::table('branches')->where('code', 'ORMOC')->value('id');

        $accounting = DB::table('users')->where('email', 'accounting@amkor.ph')->value('id');
        $coo        = DB::table('users')->where('email', 'coo@amkor.ph')->value('id');
        $gsm        = DB::table('users')->where('email', 'gsm@amkor.ph')->value('id');
        $jhona      = DB::table('users')->where('email', 'jhona@amkor.ph')->value('id');

        DB::table('collectibles')->delete();

        // ── Helper: base row defaults ──────────────────────────────────────────
        $base = [
            'source_type'                 => null,
            'source_id'                   => null,
            'contact_id'                  => null,
            'corporate_account'           => null,
            'travel_date'                 => null,
            'terms'                       => 'Net 30',
            'collectible_amount_usd'      => 0.00,
            'payment_received_usd'        => 0.00,
            'balance_usd'                 => 0.00,
            'endorsed_to_disbursement'    => false,
            'endorsed_to_disbursement_at' => null,
            'refund_processed'            => false,
            'refund_processed_at'         => null,
            'documents_endorsed'          => false,
            'documents_endorsed_at'       => null,
            'or_number'                   => null,
            'ar_number'                   => null,
            'si_number'                   => null,
            'remarks'                     => null,
            'audit_remarks'               => null,
            'approved_by_coo'             => null,
            'approved_by_coo_at'          => null,
            'approved_by_gsm'             => null,
            'approved_by_gsm_at'          => null,
            'branch_id'                   => $qcMain,
            'created_by'                  => $accounting,
            'updated_by'                  => $accounting,
            'created_at'                  => $now,
            'updated_at'                  => $now,
        ];

        $records = [

            // ══════════════════════════════════════════════════════════════════
            // RESA — CORPORATE ACCOUNTS (paid)
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'RT',
                'date'                   => '2026-01-15',
                'customer_name'          => 'Manila Solutions Corp.',
                'corporate_account'      => 'Manila Solutions Corp.',
                'particulars'            => 'Corporate Bangkok Trip — RES-2026-001 (6 pax, Feb 15–22)',
                'travel_date'            => '2026-02-15',
                'collectible_amount_php' => 156000.00,
                'payment_received_php'   => 156000.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-02-14',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-01-18 11:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-01-19 10:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-01-20 09:00:00',
                'or_number'              => 'OR-2026-001',
                'ar_number'              => 'AR-2026-001',
                'si_number'              => 'SI-2026-001',
                'remarks'                => 'Full payment received via bank transfer.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'MMT',
                'date'                   => '2026-01-22',
                'customer_name'          => 'Ayala Business Center',
                'corporate_account'      => 'Ayala Business Center',
                'particulars'            => 'HK Incentive Trip — RES-2026-002 (8 pax, Mar 3–7)',
                'travel_date'            => '2026-03-03',
                'collectible_amount_php' => 248000.00,
                'payment_received_php'   => 248000.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-02-20',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-01-25 09:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-01-26 10:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-01-27 14:00:00',
                'or_number'              => 'OR-2026-002',
                'ar_number'              => 'AR-2026-002',
                'si_number'              => 'SI-2026-002',
                'remarks'                => 'Full payment via BPI wire transfer. Docs forwarded.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'JHONA',
                'date'                   => '2026-03-08',
                'customer_name'          => 'BDO Unibank Inc.',
                'corporate_account'      => 'BDO Unibank Inc.',
                'particulars'            => 'Tokyo Executive Trip — RES-2026-005 (4 pax, Apr 5–12)',
                'travel_date'            => '2026-04-05',
                'collectible_amount_php' => 280000.00,
                'payment_received_php'   => 280000.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-03-25',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-03-10 10:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-03-11 09:30:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-03-12 14:00:00',
                'or_number'              => 'OR-2026-005',
                'ar_number'              => 'AR-2026-005',
                'si_number'              => 'SI-2026-005',
                'remarks'                => 'Full payment via BDO wire transfer.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'RT',
                'date'                   => '2026-03-20',
                'customer_name'          => 'SM Prime Holdings',
                'corporate_account'      => 'SM Prime Holdings',
                'particulars'            => 'Seoul Team Building — RES-2026-006 (10 pax, Apr 20–24)',
                'travel_date'            => '2026-04-20',
                'collectible_amount_php' => 340000.00,
                'payment_received_php'   => 340000.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-04-10',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-03-22 10:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-03-23 09:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-03-24 14:00:00',
                'or_number'              => 'OR-2026-006',
                'ar_number'              => 'AR-2026-006',
                'si_number'              => 'SI-2026-006',
                'remarks'                => 'Full settlement. OR and docs sent to SM corporate.',
                'branch_id'              => $qcMain,
            ]),

            // ══════════════════════════════════════════════════════════════════
            // RESA — PARTIAL / OVERDUE
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'MMT',
                'date'                   => '2026-02-10',
                'customer_name'          => 'Philippine Tech Inc.',
                'corporate_account'      => 'Philippine Tech Inc.',
                'particulars'            => 'Singapore Company Retreat — RES-2026-003 (9 pax, Mar 10–15)',
                'travel_date'            => '2026-03-10',
                'collectible_amount_php' => 198000.00,
                'payment_received_php'   => 99000.00,
                'balance_php'            => 99000.00,
                'due_date'               => '2026-03-01',
                'status'                 => 'overdue',
                'approval_status'        => 'coo_approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-02-15 14:00:00',
                'ar_number'              => 'AR-2026-003',
                'si_number'              => 'SI-2026-003',
                'remarks'                => '50% deposit received; balance of PHP 99,000 overdue.',
                'audit_remarks'          => 'Sent reminder email on Mar 5.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'MMT',
                'date'                   => '2026-04-12',
                'customer_name'          => 'Jollibee Foods Corporation',
                'corporate_account'      => 'Jollibee Foods Corporation',
                'particulars'            => 'KL Leadership Summit — RES-2026-007 (12 pax, May 8–11)',
                'travel_date'            => '2026-05-08',
                'collectible_amount_php' => 312000.00,
                'payment_received_php'   => 187200.00,
                'balance_php'            => 124800.00,
                'due_date'               => '2026-04-28',
                'status'                 => 'overdue',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-2026-007',
                'si_number'              => 'SI-2026-007',
                'remarks'                => '60% deposit received; PHP 124,800 balance outstanding.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'JHONA',
                'date'                   => '2026-05-05',
                'customer_name'          => 'Globe Telecom Inc.',
                'corporate_account'      => 'Globe Telecom Inc.',
                'particulars'            => 'Cebu Offsite — RES-2026-008 (7 pax, Jun 5–8)',
                'travel_date'            => '2026-06-05',
                'collectible_amount_php' => 175000.00,
                'payment_received_php'   => 87500.00,
                'balance_php'            => 87500.00,
                'due_date'               => '2026-05-28',
                'status'                 => 'overdue',
                'approval_status'        => 'coo_approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-05-07 10:00:00',
                'ar_number'              => 'AR-2026-008',
                'si_number'              => 'SI-2026-008',
                'remarks'                => '50% downpayment received; balance due May 28.',
                'audit_remarks'          => 'Globe HR acknowledged balance; processing internal PO.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // RESA — CURRENT / PENDING APPROVAL
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'RT',
                'date'                   => '2026-05-18',
                'customer_name'          => 'Ayala Land Inc.',
                'corporate_account'      => 'Ayala Land Inc.',
                'particulars'            => 'Bali Incentive Trip — RES-2026-009 (15 pax, Jun 12–17)',
                'travel_date'            => '2026-06-12',
                'collectible_amount_php' => 525000.00,
                'payment_received_php'   => 210000.00,
                'balance_php'            => 315000.00,
                'due_date'               => '2026-06-01',
                'status'                 => 'current',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-2026-009',
                'si_number'              => 'SI-2026-009',
                'remarks'                => '40% downpayment received; balance due Jun 1.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'MMT',
                'date'                   => '2026-06-02',
                'customer_name'          => 'Robinsons Land Corp.',
                'corporate_account'      => 'Robinsons Land Corp.',
                'particulars'            => 'Vietnam Sales Conference — RES-2026-010 (6 pax, Jul 10–14)',
                'travel_date'            => '2026-07-10',
                'terms'                  => 'Net 15',
                'collectible_amount_php' => 192000.00,
                'payment_received_php'   => 0.00,
                'balance_php'            => 192000.00,
                'due_date'               => '2026-06-20',
                'status'                 => 'current',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-2026-010',
                'si_number'              => 'SI-2026-010',
                'remarks'                => 'Initial SOA issued; awaiting downpayment.',
            ]),

            // ══════════════════════════════════════════════════════════════════
            // VISA — INDIVIDUAL APPLICANTS
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'JHONA',
                'date'                   => '2026-01-05',
                'customer_name'          => 'Carlos Mendoza',
                'terms'                  => 'Cash on application',
                'particulars'            => 'Japan Tourist Visa — SI-V-2026-001',
                'collectible_amount_php' => 4800.00,
                'payment_received_php'   => 4800.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-01-05',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-01-06 10:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-01-06 11:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-01-07 09:00:00',
                'or_number'              => 'OR-V-2026-001',
                'ar_number'              => 'AR-V-2026-001',
                'si_number'              => 'SI-V-2026-001',
                'remarks'                => 'Paid in cash; OR issued.',
                'branch_id'              => $visaCentre,
            ]),

            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'RT',
                'date'                   => '2026-01-13',
                'customer_name'          => 'Maria Santos',
                'terms'                  => 'Net 7',
                'particulars'            => 'UK Standard Visitor Visa — SI-V-2026-002',
                'collectible_amount_php' => 12500.00,
                'payment_received_php'   => 12500.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-01-20',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-01-14 14:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-01-15 09:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-01-16 10:00:00',
                'or_number'              => 'OR-V-2026-002',
                'ar_number'              => 'AR-V-2026-002',
                'si_number'              => 'SI-V-2026-002',
                'remarks'                => 'BDO deposit confirmed; OR issued.',
                'branch_id'              => $visaCentre,
            ]),

            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'JHONA',
                'date'                   => '2026-02-18',
                'customer_name'          => 'Ana Reyes',
                'terms'                  => 'Cash on application',
                'particulars'            => 'Australia Tourist Visa — SI-V-2026-003',
                'collectible_amount_php' => 18500.00,
                'payment_received_php'   => 18500.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-02-18',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-02-19 09:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-02-19 11:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-02-20 09:00:00',
                'or_number'              => 'OR-V-2026-003',
                'ar_number'              => 'AR-V-2026-003',
                'si_number'              => 'SI-V-2026-003',
                'remarks'                => 'Cash paid; OR issued same day.',
                'branch_id'              => $visaCentre,
            ]),

            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'RT',
                'date'                   => '2026-04-02',
                'customer_name'          => 'Marco Aquino',
                'terms'                  => 'Net 7',
                'particulars'            => 'US B1/B2 Visitor Visa — SI-V-2026-008 (incl. MRV fee)',
                'collectible_amount_php' => 18000.00,
                'collectible_amount_usd' => 245.00,
                'payment_received_php'   => 18000.00,
                'payment_received_usd'   => 245.00,
                'balance_php'            => 0.00,
                'balance_usd'            => 0.00,
                'due_date'               => '2026-04-10',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-04-04 11:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-04-05 10:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-04-06 09:00:00',
                'ar_number'              => 'AR-V-2026-008',
                'si_number'              => 'SI-V-2026-008',
                'remarks'                => 'BDO PHP portion + USD cash for MRV fee both settled.',
                'branch_id'              => $visaCentre,
            ]),

            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'JHONA',
                'date'                   => '2026-05-12',
                'customer_name'          => 'Beatrice Lim',
                'terms'                  => 'Cash on application',
                'particulars'            => 'Canada Visitor Visa — SI-V-2026-010',
                'collectible_amount_php' => 22000.00,
                'payment_received_php'   => 11000.00,
                'balance_php'            => 11000.00,
                'due_date'               => '2026-05-20',
                'status'                 => 'overdue',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-V-2026-010',
                'si_number'              => 'SI-V-2026-010',
                'remarks'                => '50% paid; client confirming balance payment method.',
                'audit_remarks'          => 'Called client May 22 — says will pay by EOM.',
                'branch_id'              => $visaCentre,
            ]),

            array_merge($base, [
                'department'             => 'visa',
                'agent_code'             => 'RT',
                'date'                   => '2026-06-05',
                'customer_name'          => 'Joseph Tan',
                'terms'                  => 'Cash on application',
                'particulars'            => 'Schengen (Italy) Tourist Visa — SI-V-2026-012',
                'collectible_amount_php' => 16500.00,
                'payment_received_php'   => 0.00,
                'balance_php'            => 16500.00,
                'due_date'               => '2026-06-15',
                'status'                 => 'current',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-V-2026-012',
                'si_number'              => 'SI-V-2026-012',
                'remarks'                => 'Application filed; payment due on OR release.',
                'branch_id'              => $visaCentre,
            ]),

            // ══════════════════════════════════════════════════════════════════
            // ORMOC BRANCH
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'ormoc',
                'agent_code'             => 'LENY',
                'date'                   => '2026-01-10',
                'customer_name'          => 'Rolando Diaz',
                'terms'                  => 'Cash on booking',
                'particulars'            => 'Cebu Weekend Trip — SI-ORM-2026-001',
                'travel_date'            => '2026-01-25',
                'collectible_amount_php' => 16500.00,
                'payment_received_php'   => 16500.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-01-08',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-01-11 10:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-01-12 09:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-01-13 14:00:00',
                'or_number'              => 'OR-ORM-2026-001',
                'ar_number'              => 'AR-ORM-2026-001',
                'si_number'              => 'SI-ORM-2026-001',
                'remarks'                => 'Cash collected at Ormoc office.',
                'branch_id'              => $ormoc,
            ]),

            array_merge($base, [
                'department'             => 'ormoc',
                'agent_code'             => 'LENY',
                'date'                   => '2026-02-05',
                'customer_name'          => 'Edgar Salas',
                'terms'                  => 'Net 15',
                'particulars'            => 'Singapore Trip (via QC RESA) — SI-ORM-2026-003',
                'travel_date'            => '2026-03-10',
                'collectible_amount_php' => 65000.00,
                'payment_received_php'   => 65000.00,
                'balance_php'            => 0.00,
                'due_date'               => '2026-02-20',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-02-06 09:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-02-07 10:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-02-08 14:00:00',
                'ar_number'              => 'AR-ORM-2026-003',
                'si_number'              => 'SI-ORM-2026-003',
                'remarks'                => 'Full payment in cash at Ormoc; OR to follow.',
                'branch_id'              => $ormoc,
            ]),

            array_merge($base, [
                'department'             => 'ormoc',
                'agent_code'             => 'LENY',
                'date'                   => '2026-04-08',
                'customer_name'          => 'Pacita Villanueva',
                'terms'                  => 'Cash on booking',
                'particulars'            => 'Boracay Family Package — SI-ORM-2026-005 (4 pax, Apr 25–28)',
                'travel_date'            => '2026-04-25',
                'collectible_amount_php' => 52000.00,
                'payment_received_php'   => 26000.00,
                'balance_php'            => 26000.00,
                'due_date'               => '2026-04-18',
                'status'                 => 'overdue',
                'approval_status'        => 'pending',
                'ar_number'              => 'AR-ORM-2026-005',
                'si_number'              => 'SI-ORM-2026-005',
                'remarks'                => '50% deposit; balance not yet settled.',
                'audit_remarks'          => 'Client says will pay Apr 30.',
                'branch_id'              => $ormoc,
            ]),

            array_merge($base, [
                'department'             => 'ormoc',
                'agent_code'             => 'LENY',
                'date'                   => '2026-05-28',
                'customer_name'          => 'Ormoc City Government',
                'corporate_account'      => 'Ormoc City Government',
                'terms'                  => 'Net 30',
                'particulars'            => 'Official Delegation — Cebu & Manila, Jun 15–20 (6 pax)',
                'travel_date'            => '2026-06-15',
                'collectible_amount_php' => 88000.00,
                'payment_received_php'   => 0.00,
                'balance_php'            => 88000.00,
                'due_date'               => '2026-06-25',
                'status'                 => 'current',
                'approval_status'        => 'pending',
                'si_number'              => 'SI-ORM-2026-007',
                'remarks'                => 'LGU purchase order attached; awaiting approval.',
                'branch_id'              => $ormoc,
            ]),

            // ══════════════════════════════════════════════════════════════════
            // SPECIAL — USD & IBAYAD
            // ══════════════════════════════════════════════════════════════════
            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'RT',
                'date'                   => '2026-03-25',
                'customer_name'          => 'Pacific Rim Investments',
                'corporate_account'      => 'Pacific Rim Investments',
                'terms'                  => 'Net 30',
                'particulars'            => 'Sydney Conference — RES-2026-004 (3 pax, Apr 28 – May 2)',
                'travel_date'            => '2026-04-28',
                'collectible_amount_php' => 45000.00,
                'collectible_amount_usd' => 1800.00,
                'payment_received_php'   => 45000.00,
                'payment_received_usd'   => 1800.00,
                'balance_php'            => 0.00,
                'balance_usd'            => 0.00,
                'due_date'               => '2026-04-15',
                'status'                 => 'paid',
                'approval_status'        => 'approved',
                'approved_by_coo'        => $coo,
                'approved_by_coo_at'     => '2026-03-27 10:00:00',
                'approved_by_gsm'        => $gsm,
                'approved_by_gsm_at'     => '2026-03-28 09:00:00',
                'documents_endorsed'     => true,
                'documents_endorsed_at'  => '2026-03-29 14:00:00',
                'or_number'              => 'OR-2026-004',
                'ar_number'              => 'AR-2026-004',
                'si_number'              => 'SI-2026-004',
                'remarks'                => 'PHP portion bank transfer; USD settled in cash.',
            ]),

            array_merge($base, [
                'department'             => 'resa',
                'agent_code'             => 'MMT',
                'date'                   => '2026-05-30',
                'customer_name'          => 'Metrobank Cards Corp.',
                'corporate_account'      => 'Metrobank Cards Corp.',
                'terms'                  => 'Net 15',
                'particulars'            => 'Executive Osaka Trip — RES-2026-011 (2 pax, Jul 8–14)',
                'travel_date'            => '2026-07-08',
                'collectible_amount_php' => 0.00,
                'collectible_amount_usd' => 3200.00,
                'payment_received_php'   => 0.00,
                'payment_received_usd'   => 0.00,
                'balance_php'            => 0.00,
                'balance_usd'            => 3200.00,
                'due_date'               => '2026-06-20',
                'status'                 => 'ibayad',
                'approval_status'        => 'pending',
                'si_number'              => 'SI-2026-011',
                'remarks'                => 'USD invoice issued; client prefers USD settlement.',
            ]),
        ];

        DB::table('collectibles')->insert($records);
    }
}
