<?php

namespace Modules\Visa\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VisaDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $qcMain  = DB::table('branches')->where('code', 'QC_MAIN')->value('id');

        $visa    = DB::table('users')->where('email', 'alex@amkor.ph')->value('id');
        $liaison = DB::table('users')->where('email', 'randy@amkor.ph')->value('id');
        $gsm     = DB::table('users')->where('email', 'rochelle@amkor.ph')->value('id');

        // ── Visa Applications ───────────────────────────────────────────────────
        DB::table('visa_applications')->delete();

        $applications = [
            [
                'agent_code'              => 'ALEX',
                'date'                    => '2026-01-05',
                'agency'                  => null,
                'embassy_name'            => 'Japan Embassy Manila',
                'customer_name'           => 'Roberto Aquino',
                'date_of_birth'           => '1988-03-14',
                'visa_type'               => 'Japan Visa',
                'selling_price'           => 12000.00,
                'net_payable'             => 8500.00,
                'income'                  => 3500.00,
                'status'                  => 'completed',
                'notes'                   => null,
                'mode_of_payment'         => 'cash',
                'payment_date'            => '2026-01-05',
                'payment_cash'            => 12000.00,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-001',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-01-06 09:00:00',
                'payable_cash'            => 8500.00,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => 'OR-V-2026-001',
                'cv_number'               => 'CV-2026-009',
                'date_requested'          => '2026-01-06',
                'or_received_at'          => '2026-01-10 10:00:00',
                'or_endorsed_at'          => '2026-01-11 14:00:00',
                'or_endorsed_by'          => $liaison,
                'courier_name'            => 'Grab Padala',
                'date_received'           => '2026-01-10',
                'date_filed'              => '2026-01-06',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'RICCI',
                'date'                    => '2026-01-15',
                'agency'                  => null,
                'embassy_name'            => 'Korean Embassy Manila',
                'customer_name'           => 'Patricia Cruz',
                'date_of_birth'           => '1992-06-21',
                'visa_type'               => 'Korea Visa',
                'selling_price'           => 10000.00,
                'net_payable'             => 7000.00,
                'income'                  => 3000.00,
                'status'                  => 'completed',
                'notes'                   => null,
                'mode_of_payment'         => 'bdo',
                'payment_date'            => '2026-01-15',
                'payment_cash'            => null,
                'payment_bdo'             => 10000.00,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => 'SOA-V-2026-002',
                'si_number'               => 'SI-V-2026-002',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-01-16 09:00:00',
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => 7000.00,
                'payable_credit_card'     => null,
                'or_number'               => 'OR-V-2026-002',
                'cv_number'               => 'CV-2026-010',
                'date_requested'          => '2026-01-16',
                'or_received_at'          => '2026-01-20 10:00:00',
                'or_endorsed_at'          => '2026-01-21 14:00:00',
                'or_endorsed_by'          => $liaison,
                'courier_name'            => '2GO Express',
                'date_received'           => '2026-01-20',
                'date_filed'              => '2026-01-16',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'MEL',
                'date'                    => '2026-02-01',
                'agency'                  => null,
                'embassy_name'            => 'US Embassy Manila',
                'customer_name'           => 'Angelo Bautista',
                'date_of_birth'           => '1980-12-02',
                'visa_type'               => 'US Visa',
                'selling_price'           => 15000.00,
                'net_payable'             => 10500.00,
                'income'                  => 4500.00,
                'status'                  => 'on_process',
                'notes'                   => 'Interview scheduled at US Embassy for Feb 25.',
                'mode_of_payment'         => 'cash',
                'payment_date'            => '2026-02-01',
                'payment_cash'            => 15000.00,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-003',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => false,
                'payment_request_sent_at' => null,
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => null,
                'date_requested'          => null,
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => '2026-02-02',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'KAE',
                'date'                    => '2026-02-10',
                'agency'                  => null,
                'embassy_name'            => 'Japan Embassy Manila',
                'customer_name'           => 'Carmen Villanueva',
                'date_of_birth'           => '1975-01-29',
                'visa_type'               => 'Japan Commercial Visa',
                'selling_price'           => 13000.00,
                'net_payable'             => 9100.00,
                'income'                  => 3900.00,
                'status'                  => 'on_process',
                'notes'                   => null,
                'mode_of_payment'         => 'bpi',
                'payment_date'            => '2026-02-10',
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => 13000.00,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => 'SOA-V-2026-004',
                'si_number'               => 'SI-V-2026-004',
                'ar_number'               => null,
                'payment_due_date'        => '2026-03-10',
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-02-20 09:00:00',
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => 'CV-2026-011',
                'date_requested'          => '2026-02-20',
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => '2026-02-21',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'MIMI',
                'date'                    => '2026-02-20',
                'agency'                  => null,
                'embassy_name'            => 'Italian Embassy Manila',
                'customer_name'           => 'Emmanuel Garcia',
                'date_of_birth'           => '1990-05-08',
                'visa_type'               => 'Italy Visa',
                'selling_price'           => 18000.00,
                'net_payable'             => 12600.00,
                'income'                  => 5400.00,
                'status'                  => 'pending',
                'notes'                   => 'Waiting for client to submit complete financial documents.',
                'mode_of_payment'         => null,
                'payment_date'            => null,
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => null,
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => false,
                'payment_request_sent_at' => null,
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => null,
                'date_requested'          => null,
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => null,
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'MMT',
                'date'                    => '2026-03-01',
                'agency'                  => 'Mariposa Travel Agency',
                'embassy_name'            => 'Australian Visa Application Centre',
                'customer_name'           => 'Liza Ramos',
                'date_of_birth'           => '1986-10-17',
                'visa_type'               => 'Australia Visa',
                'selling_price'           => 14000.00,
                'net_payable'             => 9800.00,
                'income'                  => 4200.00,
                'status'                  => 'completed',
                'notes'                   => null,
                'mode_of_payment'         => 'cash',
                'payment_date'            => '2026-03-01',
                'payment_cash'            => 14000.00,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-006',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-03-02 09:00:00',
                'payable_cash'            => 9800.00,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => 'OR-V-2026-006',
                'cv_number'               => 'CV-2026-012',
                'date_requested'          => '2026-03-02',
                'or_received_at'          => '2026-03-05 10:00:00',
                'or_endorsed_at'          => '2026-03-06 14:00:00',
                'or_endorsed_by'          => $liaison,
                'courier_name'            => 'Grab Padala',
                'date_received'           => '2026-03-05',
                'date_filed'              => '2026-03-02',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'ALEX',
                'date'                    => '2026-03-15',
                'agency'                  => null,
                'embassy_name'            => 'Japan Embassy Manila',
                'customer_name'           => 'Francis Mendoza',
                'date_of_birth'           => '1983-07-25',
                'visa_type'               => 'Japan Visa',
                'selling_price'           => 12000.00,
                'net_payable'             => 8500.00,
                'income'                  => 3500.00,
                'status'                  => 'approved',
                'notes'                   => 'Visa approved; awaiting passport release from embassy.',
                'mode_of_payment'         => 'cash',
                'payment_date'            => '2026-03-15',
                'payment_cash'            => 12000.00,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-007',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-03-16 09:00:00',
                'payable_cash'            => 8500.00,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => 'OR-V-2026-007',
                'cv_number'               => 'CV-2026-013',
                'date_requested'          => '2026-03-16',
                'or_received_at'          => '2026-03-20 10:00:00',
                'or_endorsed_at'          => '2026-03-21 14:00:00',
                'or_endorsed_by'          => $liaison,
                'courier_name'            => 'Japan Embassy pickup',
                'date_received'           => '2026-03-20',
                'date_filed'              => '2026-03-16',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'RICCI',
                'date'                    => '2026-04-01',
                'agency'                  => null,
                'embassy_name'            => 'Korean Embassy Manila',
                'customer_name'           => 'Grace Tan',
                'date_of_birth'           => '1979-04-30',
                'visa_type'               => 'Korea Visa',
                'selling_price'           => 10000.00,
                'net_payable'             => 7000.00,
                'income'                  => 3000.00,
                'status'                  => 'on_process',
                'notes'                   => null,
                'mode_of_payment'         => 'check',
                'payment_date'            => '2026-04-01',
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => 10000.00,
                'soa_number'              => 'SOA-V-2026-008',
                'si_number'               => 'SI-V-2026-008',
                'ar_number'               => 'AR-V-2026-008',
                'payment_due_date'        => '2026-05-01',
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-04-10 09:00:00',
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => 'CV-2026-014',
                'date_requested'          => '2026-04-10',
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => '2026-04-11',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'MEL',
                'date'                    => '2026-04-15',
                'agency'                  => null,
                'embassy_name'            => 'Canadian Visa Application Centre',
                'customer_name'           => 'Daniel Lim',
                'date_of_birth'           => '1991-11-09',
                'visa_type'               => 'Canada Visa',
                'selling_price'           => 16000.00,
                'net_payable'             => 11200.00,
                'income'                  => 4800.00,
                'status'                  => 'denied',
                'notes'                   => 'Application denied by embassy — insufficient proof of financial capacity. Client informed Apr 30; no refund on embassy filing fee per policy.',
                'mode_of_payment'         => 'cash',
                'payment_date'            => '2026-04-15',
                'payment_cash'            => 16000.00,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-009',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-04-16 09:00:00',
                'payable_cash'            => 11200.00,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => 'CV-2026-015',
                'date_requested'          => '2026-04-16',
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => '2026-04-17',
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'KAE',
                'date'                    => '2026-05-01',
                'agency'                  => null,
                'embassy_name'            => 'Japan Embassy Manila',
                'customer_name'           => 'Michelle Santos',
                'date_of_birth'           => '1996-02-12',
                'visa_type'               => 'Japan Visa',
                'selling_price'           => 12000.00,
                'net_payable'             => 8500.00,
                'income'                  => 3500.00,
                'status'                  => 'pending',
                'notes'                   => null,
                'mode_of_payment'         => null,
                'payment_date'            => null,
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => null,
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => false,
                'payment_request_sent_at' => null,
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => null,
                'date_requested'          => null,
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => null,
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'MIMI',
                'date'                    => '2026-05-12',
                'agency'                  => null,
                'embassy_name'            => null,
                'customer_name'           => 'Bernardo Castillo',
                'date_of_birth'           => '1970-09-04',
                'visa_type'               => 'Cash Bond',
                'selling_price'           => 250000.00,
                'net_payable'             => 250000.00,
                'income'                  => 8000.00,
                'status'                  => 'completed',
                'notes'                   => 'Cash bond posted for tourist visa application; fully refundable to client upon return.',
                'mode_of_payment'         => 'metrobank',
                'payment_date'            => '2026-05-12',
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => 250000.00,
                'payment_card'            => null,
                'payment_check'           => null,
                'soa_number'              => 'SOA-V-2026-011',
                'si_number'               => 'SI-V-2026-011',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => true,
                'payment_request_sent_at' => '2026-05-13 09:00:00',
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => 250000.00,
                'payable_credit_card'     => null,
                'or_number'               => 'OR-V-2026-011',
                'cv_number'               => 'CV-2026-016',
                'date_requested'          => '2026-05-13',
                'or_received_at'          => '2026-05-15 10:00:00',
                'or_endorsed_at'          => '2026-05-16 14:00:00',
                'or_endorsed_by'          => $liaison,
                'courier_name'            => null,
                'date_received'           => '2026-05-15',
                'date_filed'              => null,
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'agent_code'              => 'RICCI',
                'date'                    => '2026-05-20',
                'agency'                  => null,
                'embassy_name'            => 'India Visa Online',
                'customer_name'           => 'Tessa Domingo',
                'date_of_birth'           => '1989-01-21',
                'visa_type'               => 'India E-Visa',
                'selling_price'           => 4500.00,
                'net_payable'             => 3000.00,
                'income'                  => 1500.00,
                'status'                  => 'forfeited',
                'notes'                   => 'Client did not provide complete documents within 30-day window; processing fee forfeited per policy.',
                'mode_of_payment'         => 'card',
                'payment_date'            => '2026-05-20',
                'payment_cash'            => null,
                'payment_bdo'             => null,
                'payment_bpi'             => null,
                'payment_metrobank'       => null,
                'payment_card'            => 4500.00,
                'payment_check'           => null,
                'soa_number'              => null,
                'si_number'               => 'SI-V-2026-012',
                'ar_number'               => null,
                'payment_due_date'        => null,
                'payment_request_sent'    => false,
                'payment_request_sent_at' => null,
                'payable_cash'            => null,
                'payable_cash_usd'        => null,
                'payable_bank_deposit'    => null,
                'payable_credit_card'     => null,
                'or_number'               => null,
                'cv_number'               => null,
                'date_requested'          => null,
                'or_received_at'          => null,
                'or_endorsed_at'          => null,
                'or_endorsed_by'          => null,
                'courier_name'            => null,
                'date_received'           => null,
                'date_filed'              => null,
                'branch_id'               => $qcMain,
                'created_by'              => $visa,
                'updated_by'              => $visa,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
        ];

        DB::table('visa_applications')->insert($applications);

        // ── Visa Monthly Income Targets ─────────────────────────────────────────
        DB::table('visa_targets')->delete();

        $targets = [
            ['month' => 1, 'year' => 2026, 'income_target' => 700000.00, 'sp_target' => 1900000.00, 'np_target' => 1300000.00, 'notes' => null],
            ['month' => 2, 'year' => 2026, 'income_target' => 700000.00, 'sp_target' => 1900000.00, 'np_target' => 1300000.00, 'notes' => null],
            ['month' => 3, 'year' => 2026, 'income_target' => 700000.00, 'sp_target' => 1900000.00, 'np_target' => 1300000.00, 'notes' => null],
            ['month' => 4, 'year' => 2026, 'income_target' => 750000.00, 'sp_target' => 2000000.00, 'np_target' => 1350000.00, 'notes' => 'Target raised for summer travel season.'],
            ['month' => 5, 'year' => 2026, 'income_target' => 750000.00, 'sp_target' => 2000000.00, 'np_target' => 1350000.00, 'notes' => null],
            ['month' => 6, 'year' => 2026, 'income_target' => 750000.00, 'sp_target' => 2000000.00, 'np_target' => 1350000.00, 'notes' => null],
        ];

        foreach ($targets as $target) {
            DB::table('visa_targets')->insert(array_merge($target, [
                'created_by' => $gsm,
                'updated_by' => $gsm,
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
